### ISSUE TITLE
Question regarding the model input

### ISSUE THREAD

**Issue by zwep** [mirzaevinom/prostate_segmentation#3]
Hello there,

first time commenting on a repo here, so if this is not the right place to do so please let me know.

Okay, so what I was aiming to do is to score a picture of my own database with your model and see how it performs:
![my_input](https://user-images.githubusercontent.com/26649804/40375940-598897d8-5ded-11e8-95b3-7a1de7a0a275.png)

 I got my image from one of the patients in the ProstateX challenge. (link http://www.spie.org/PROSTATEx/)
Here I selected an image in the transversal plane of the prostate of a patient, by inspection you could see that it was similar to the test cases your showed in the README.md.

After loading your model and the associated weights I started to prep my own input image.
First load it, then rescale it to (1, 96, 96, 1) and use the model.predict() function to generate an output.
However, was a matrix consisting of mainly zeroes, no segmentation to be found!
![my_output](https://user-images.githubusercontent.com/26649804/40375875-2282072e-5ded-11e8-9022-a7608277b03f.png)

So to be sure that the model worked, I copied, cut and pasted your example images, loaded them in Python, scaled it to (1, 96, 96, 1) and gave it to the model:
![mirzaevinom_input](https://user-images.githubusercontent.com/26649804/40375957-6345f4a0-5ded-11e8-8b45-76dbdc4c9514.png)

Et Voila, a well formed output just as given in your README file. 
![mirzaevinom_output](https://user-images.githubusercontent.com/26649804/40375882-2a1fb044-5ded-11e8-9b5c-9bab17f815d8.png)

Conclusion... the model that I loaded with the weights works. But somehow my image is not working properly.

Thinking about my image format, I tried the following techniques
- scale it to 0...255
- scale it to 0...1
- equalize it using cv2.equalizeHist
- equalize it using cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))

all with no satisfactory result... 
Is this a sign that the model has overfit? Am I doing something wrong? Any other cause?? Am I using the right input? (I am just starting with all this medical data, so I cant 'read' those MRI images properly..)

PS, this is the code that I used...
model = simple_unet(96, 96)
model.load_weights(r'..\simple_unet_weights.h5')
a1 = Image.open(r'..\my_example.jpg').convert('LA')
a1 = np.array(a1)[:,:,0]
plt.imshow(a1, cmap=plt.cm.gray)
plt.show()
b1 = skimage.transform.resize(a1, (96, 96))
b1 = b1/np.max(b1)
plt.imshow(b1, cmap=plt.cm.gray)
plt.show()
plt.hist(b1.ravel())
plt.show()
c1 = np.reshape(b1, (1,96,96,1))

# Predict with the image..
res_c1 = model.predict(c1)
res_d1 = np.reshape(res_c1, (96,96))

plt.imshow(res_d1, cmap=plt.cm.gray)
plt.show()

**Comment by mirzaevinom** [comment]
Sorry for the late response @zwep. See `dicom_to_array` function for the input pre-processing. I just use standard histogram equalization. Basically, after reading the MR image, do the following
```  
from skimage.exposure import equalize_hist
img = equalize_hist( img.astype(int) )
```

Hope it helps,
Inom

**Comment by zwep** [comment]
Thanks, will try some more in the afternoon! 

EDIT: @mirzaevinom worked like a charm, thanks man :)
